apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-che
  labels:
    app: sf-che-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sf-che-api
  template:
    metadata:
      labels:
        app: sf-che-api
    spec:
      imagePullSecrets:
      - name: ghcr
      containers:
      - name: sf-che-api
        image: ghcr.io/datewu/sf-che.back:v0.0.6
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 4000
          name: api

---
apiVersion: v1
kind: Service
metadata:
  name: sf-che-api
# namespace: wu
spec:
  selector:
    app: sf-che-api
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: sf-che-api
spec:
  ingressClassName: public
  rules:
  - host: api.sf-che.com
    http:
      paths:
      - backend:
          service:
            name: sf-che-api
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api.sf-che.com
    secretName: api.sf-che.com.tls
